/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackersRouteImport } from './routes/trackers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as HiringRouteImport } from './routes/hiring'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as MediaReelsRouteImport } from './routes/media.reels'
import { Route as MarketplaceOrdersRouteImport } from './routes/marketplace.orders'
import { Route as MarketplaceNewRouteImport } from './routes/marketplace.new'
import { Route as MarketplaceCheckoutReturnRouteImport } from './routes/marketplace.checkout-return'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as MediaReelsStudioRouteImport } from './routes/media.reels.studio'
import { Route as MediaReelsReelIdRouteImport } from './routes/media.reels.$reelId'
import { Route as MarketplaceGigSlugRouteImport } from './routes/marketplace.gig.$slug'

const TrackersRoute = TrackersRouteImport.update({
  id: '/trackers',
  path: '/trackers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringRoute = HiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaReelsRoute = MediaReelsRouteImport.update({
  id: '/media/reels',
  path: '/media/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceOrdersRoute = MarketplaceOrdersRouteImport.update({
  id: '/marketplace/orders',
  path: '/marketplace/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceNewRoute = MarketplaceNewRouteImport.update({
  id: '/marketplace/new',
  path: '/marketplace/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCheckoutReturnRoute =
  MarketplaceCheckoutReturnRouteImport.update({
    id: '/marketplace/checkout-return',
    path: '/marketplace/checkout-return',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaReelsStudioRoute = MediaReelsStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => MediaReelsRoute,
} as any)
const MediaReelsReelIdRoute = MediaReelsReelIdRouteImport.update({
  id: '/$reelId',
  path: '/$reelId',
  getParentRoute: () => MediaReelsRoute,
} as any)
const MarketplaceGigSlugRoute = MarketplaceGigSlugRouteImport.update({
  id: '/marketplace/gig/$slug',
  path: '/marketplace/gig/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/hiring': typeof HiringRoute
  '/inbox': typeof InboxRoute
  '/notifications': typeof NotificationsRoute
  '/trackers': typeof TrackersRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/jobs/new': typeof JobsNewRoute
  '/marketplace/checkout-return': typeof MarketplaceCheckoutReturnRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/marketplace/orders': typeof MarketplaceOrdersRoute
  '/media/reels': typeof MediaReelsRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/jobs/': typeof JobsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/marketplace/gig/$slug': typeof MarketplaceGigSlugRoute
  '/media/reels/$reelId': typeof MediaReelsReelIdRoute
  '/media/reels/studio': typeof MediaReelsStudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/hiring': typeof HiringRoute
  '/inbox': typeof InboxRoute
  '/notifications': typeof NotificationsRoute
  '/trackers': typeof TrackersRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/jobs/new': typeof JobsNewRoute
  '/marketplace/checkout-return': typeof MarketplaceCheckoutReturnRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/marketplace/orders': typeof MarketplaceOrdersRoute
  '/media/reels': typeof MediaReelsRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/jobs': typeof JobsIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/marketplace/gig/$slug': typeof MarketplaceGigSlugRoute
  '/media/reels/$reelId': typeof MediaReelsReelIdRoute
  '/media/reels/studio': typeof MediaReelsStudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/explore': typeof ExploreRoute
  '/feed': typeof FeedRoute
  '/hiring': typeof HiringRoute
  '/inbox': typeof InboxRoute
  '/notifications': typeof NotificationsRoute
  '/trackers': typeof TrackersRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/jobs/new': typeof JobsNewRoute
  '/marketplace/checkout-return': typeof MarketplaceCheckoutReturnRoute
  '/marketplace/new': typeof MarketplaceNewRoute
  '/marketplace/orders': typeof MarketplaceOrdersRoute
  '/media/reels': typeof MediaReelsRouteWithChildren
  '/u/$username': typeof UUsernameRoute
  '/jobs/': typeof JobsIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/marketplace/gig/$slug': typeof MarketplaceGigSlugRoute
  '/media/reels/$reelId': typeof MediaReelsReelIdRoute
  '/media/reels/studio': typeof MediaReelsStudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/explore'
    | '/feed'
    | '/hiring'
    | '/inbox'
    | '/notifications'
    | '/trackers'
    | '/jobs/$slug'
    | '/jobs/new'
    | '/marketplace/checkout-return'
    | '/marketplace/new'
    | '/marketplace/orders'
    | '/media/reels'
    | '/u/$username'
    | '/jobs/'
    | '/marketplace/'
    | '/marketplace/gig/$slug'
    | '/media/reels/$reelId'
    | '/media/reels/studio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/explore'
    | '/feed'
    | '/hiring'
    | '/inbox'
    | '/notifications'
    | '/trackers'
    | '/jobs/$slug'
    | '/jobs/new'
    | '/marketplace/checkout-return'
    | '/marketplace/new'
    | '/marketplace/orders'
    | '/media/reels'
    | '/u/$username'
    | '/jobs'
    | '/marketplace'
    | '/marketplace/gig/$slug'
    | '/media/reels/$reelId'
    | '/media/reels/studio'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/explore'
    | '/feed'
    | '/hiring'
    | '/inbox'
    | '/notifications'
    | '/trackers'
    | '/jobs/$slug'
    | '/jobs/new'
    | '/marketplace/checkout-return'
    | '/marketplace/new'
    | '/marketplace/orders'
    | '/media/reels'
    | '/u/$username'
    | '/jobs/'
    | '/marketplace/'
    | '/marketplace/gig/$slug'
    | '/media/reels/$reelId'
    | '/media/reels/studio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ExploreRoute: typeof ExploreRoute
  FeedRoute: typeof FeedRoute
  HiringRoute: typeof HiringRoute
  InboxRoute: typeof InboxRoute
  NotificationsRoute: typeof NotificationsRoute
  TrackersRoute: typeof TrackersRoute
  JobsSlugRoute: typeof JobsSlugRoute
  JobsNewRoute: typeof JobsNewRoute
  MarketplaceCheckoutReturnRoute: typeof MarketplaceCheckoutReturnRoute
  MarketplaceNewRoute: typeof MarketplaceNewRoute
  MarketplaceOrdersRoute: typeof MarketplaceOrdersRoute
  MediaReelsRoute: typeof MediaReelsRouteWithChildren
  UUsernameRoute: typeof UUsernameRoute
  JobsIndexRoute: typeof JobsIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceGigSlugRoute: typeof MarketplaceGigSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trackers': {
      id: '/trackers'
      path: '/trackers'
      fullPath: '/trackers'
      preLoaderRoute: typeof TrackersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring': {
      id: '/hiring'
      path: '/hiring'
      fullPath: '/hiring'
      preLoaderRoute: typeof HiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/reels': {
      id: '/media/reels'
      path: '/media/reels'
      fullPath: '/media/reels'
      preLoaderRoute: typeof MediaReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/orders': {
      id: '/marketplace/orders'
      path: '/marketplace/orders'
      fullPath: '/marketplace/orders'
      preLoaderRoute: typeof MarketplaceOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/new': {
      id: '/marketplace/new'
      path: '/marketplace/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof MarketplaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/checkout-return': {
      id: '/marketplace/checkout-return'
      path: '/marketplace/checkout-return'
      fullPath: '/marketplace/checkout-return'
      preLoaderRoute: typeof MarketplaceCheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/reels/studio': {
      id: '/media/reels/studio'
      path: '/studio'
      fullPath: '/media/reels/studio'
      preLoaderRoute: typeof MediaReelsStudioRouteImport
      parentRoute: typeof MediaReelsRoute
    }
    '/media/reels/$reelId': {
      id: '/media/reels/$reelId'
      path: '/$reelId'
      fullPath: '/media/reels/$reelId'
      preLoaderRoute: typeof MediaReelsReelIdRouteImport
      parentRoute: typeof MediaReelsRoute
    }
    '/marketplace/gig/$slug': {
      id: '/marketplace/gig/$slug'
      path: '/marketplace/gig/$slug'
      fullPath: '/marketplace/gig/$slug'
      preLoaderRoute: typeof MarketplaceGigSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MediaReelsRouteChildren {
  MediaReelsReelIdRoute: typeof MediaReelsReelIdRoute
  MediaReelsStudioRoute: typeof MediaReelsStudioRoute
}

const MediaReelsRouteChildren: MediaReelsRouteChildren = {
  MediaReelsReelIdRoute: MediaReelsReelIdRoute,
  MediaReelsStudioRoute: MediaReelsStudioRoute,
}

const MediaReelsRouteWithChildren = MediaReelsRoute._addFileChildren(
  MediaReelsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ExploreRoute: ExploreRoute,
  FeedRoute: FeedRoute,
  HiringRoute: HiringRoute,
  InboxRoute: InboxRoute,
  NotificationsRoute: NotificationsRoute,
  TrackersRoute: TrackersRoute,
  JobsSlugRoute: JobsSlugRoute,
  JobsNewRoute: JobsNewRoute,
  MarketplaceCheckoutReturnRoute: MarketplaceCheckoutReturnRoute,
  MarketplaceNewRoute: MarketplaceNewRoute,
  MarketplaceOrdersRoute: MarketplaceOrdersRoute,
  MediaReelsRoute: MediaReelsRouteWithChildren,
  UUsernameRoute: UUsernameRoute,
  JobsIndexRoute: JobsIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceGigSlugRoute: MarketplaceGigSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
